import { StudentProfile, GroupOption, Course, SemesterRecord, ComprobanteRecord } from '../types';

export const INITIAL_STUDENT: StudentProfile = {
  matricula: '2022452139',
  nombre: 'Irvin Osvaldo Gálvez Romero',
  nombreCorto: 'Irvin Gálvez',
  carrera: 'Ingeniería en Sistemas Computacionales',
  periodoActual: 'Septiembre - Enero 2026-2027',
  semestreActual: '9º Semestre',
  promedioGeneral: 9.6,
  creditosAcumulados: 235,
  creditosTotales: 260,
  avancePorcentaje: 90,
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  email: '2022452139@teschi.edu.mx',
  status: 'regular',
  biometricsRegistered: true,
};

export const STUDENT_6TH: StudentProfile = {
  matricula: '2022452167',
  nombre: 'Mishelle Stefania',
  nombreCorto: 'Mishelle',
  carrera: 'Ingeniería en Sistemas Computacionales',
  periodoActual: 'Septiembre - Enero 2026-2027',
  semestreActual: '6º Semestre',
  promedioGeneral: 9.3,
  creditosAcumulados: 172,
  creditosTotales: 260,
  avancePorcentaje: 66,
  avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
  email: '2022452167@teschi.edu.mx',
  status: 'regular',
  biometricsRegistered: true,
};

export const STUDENT_DANIELA: StudentProfile = {
  matricula: '2022222103',
  nombre: 'Hernández Martínez, Daniela',
  nombreCorto: 'Daniela',
  carrera: 'Licenciatura en Administración',
  periodoActual: 'Septiembre - Enero 2026-2027',
  semestreActual: '6º Semestre',
  promedioGeneral: 9.5,
  creditosAcumulados: 170,
  creditosTotales: 260,
  avancePorcentaje: 65,
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
  email: '2022222103@teschi.edu.mx',
  status: 'regular',
  biometricsRegistered: true,
};

export const STUDENT_4TH: StudentProfile = {
  matricula: '2023450412',
  nombre: 'Morales Ruiz, Fernando',
  nombreCorto: 'Fernando Morales',
  carrera: 'Ingeniería en Sistemas Computacionales',
  periodoActual: 'Septiembre - Enero 2026-2027',
  semestreActual: '4º Semestre',
  promedioGeneral: 9.1,
  creditosAcumulados: 108,
  creditosTotales: 260,
  avancePorcentaje: 41,
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
  email: '2023450412@teschi.edu.mx',
  status: 'regular',
  biometricsRegistered: true,
};

export const AVAILABLE_GROUPS: GroupOption[] = [
  // --- GRUPOS 9º SEMESTRE (Para reinscripción a 9no) ---
  {
    id: '9ISC11',
    claveGrupo: '9ISC11',
    nombre: 'Grupo 9ISC11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 25,
    cupoMaximo: 35,
    semestre: '9º Semestre',
    semestreNumero: 9,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '9ISC21',
    claveGrupo: '9ISC21',
    nombre: 'Grupo 9ISC21 - Vespertino',
    turno: 'Vespertino',
    horarioResumen: '14:00 a 20:00 hrs (Lun a Vie)',
    cupoDisponible: 20,
    cupoMaximo: 35,
    semestre: '9º Semestre',
    semestreNumero: 9,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  // --- GRUPOS 6º SEMESTRE (Para reinscripción a 6to) ---
  {
    id: '6ISC11',
    claveGrupo: '6ISC11',
    nombre: 'Grupo 6ISC11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 16,
    cupoMaximo: 35,
    semestre: '6º Semestre',
    semestreNumero: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '6ISC12',
    claveGrupo: '6ISC12',
    nombre: 'Grupo 6ISC12 - Matutino',
    turno: 'Matutino',
    horarioResumen: '08:00 a 14:00 hrs (Lun a Vie)',
    cupoDisponible: 14,
    cupoMaximo: 35,
    semestre: '6º Semestre',
    semestreNumero: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '6ISC21',
    claveGrupo: '6ISC21',
    nombre: 'Grupo 6ISC21 - Vespertino',
    turno: 'Vespertino',
    horarioResumen: '14:00 a 20:00 hrs (Lun a Vie)',
    cupoDisponible: 22,
    cupoMaximo: 35,
    semestre: '6º Semestre',
    semestreNumero: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '4ISC11',
    claveGrupo: '4ISC11',
    nombre: 'Grupo 4ISC11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 8,
    cupoMaximo: 35,
    semestre: '4º Semestre',
    semestreNumero: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '4ISC12',
    claveGrupo: '4ISC12',
    nombre: 'Grupo 4ISC12 - Matutino',
    turno: 'Matutino',
    horarioResumen: '08:00 a 14:00 hrs (Lun a Vie)',
    cupoDisponible: 14,
    cupoMaximo: 35,
    semestre: '4º Semestre',
    semestreNumero: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '4ISC21',
    claveGrupo: '4ISC21',
    nombre: 'Grupo 4ISC21 - Vespertino',
    turno: 'Vespertino',
    horarioResumen: '14:00 a 20:00 hrs (Lun a Vie)',
    cupoDisponible: 21,
    cupoMaximo: 35,
    semestre: '4º Semestre',
    semestreNumero: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '2ISC11',
    claveGrupo: '2ISC11',
    nombre: 'Grupo 2ISC11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 12,
    cupoMaximo: 35,
    semestre: '2º Semestre',
    semestreNumero: 2,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '8ISC11',
    claveGrupo: '8ISC11',
    nombre: 'Grupo 8ISC11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 19,
    cupoMaximo: 35,
    semestre: '8º Semestre',
    semestreNumero: 8,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  // --- GRUPOS 5º SEMESTRE ISC ---
  {
    id: '5ISC11',
    claveGrupo: '5ISC11',
    nombre: 'Grupo 5ISC11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 17,
    cupoMaximo: 35,
    semestre: '5º Semestre',
    semestreNumero: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  {
    id: '5ISC21',
    claveGrupo: '5ISC21',
    nombre: 'Grupo 5ISC21 - Vespertino',
    turno: 'Vespertino',
    horarioResumen: '14:00 a 20:00 hrs (Lun a Vie)',
    cupoDisponible: 24,
    cupoMaximo: 35,
    semestre: '5º Semestre',
    semestreNumero: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
  },
  // --- GRUPOS LICENCIATURA EN ADMINISTRACIÓN (LAD) ---
  {
    id: '4LAD11',
    claveGrupo: '4LAD11',
    nombre: 'Grupo 4LAD11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 18,
    cupoMaximo: 35,
    semestre: '4º Semestre',
    semestreNumero: 4,
    carrera: 'Licenciatura en Administración',
  },
  {
    id: '4LAD21',
    claveGrupo: '4LAD21',
    nombre: 'Grupo 4LAD21 - Vespertino',
    turno: 'Vespertino',
    horarioResumen: '14:00 a 20:00 hrs (Lun a Vie)',
    cupoDisponible: 22,
    cupoMaximo: 35,
    semestre: '4º Semestre',
    semestreNumero: 4,
    carrera: 'Licenciatura en Administración',
  },
  {
    id: '5LAD11',
    claveGrupo: '5LAD11',
    nombre: 'Grupo 5LAD11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 15,
    cupoMaximo: 35,
    semestre: '5º Semestre',
    semestreNumero: 5,
    carrera: 'Licenciatura en Administración',
  },
  {
    id: '6LAD11',
    claveGrupo: '6LAD11',
    nombre: 'Grupo 6LAD11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 20,
    cupoMaximo: 35,
    semestre: '6º Semestre',
    semestreNumero: 6,
    carrera: 'Licenciatura en Administración',
  },
  {
    id: '6LAD12',
    claveGrupo: '6LAD12',
    nombre: 'Grupo 6LAD12 - Matutino',
    turno: 'Matutino',
    horarioResumen: '08:00 a 14:00 hrs (Lun a Vie)',
    cupoDisponible: 16,
    cupoMaximo: 35,
    semestre: '6º Semestre',
    semestreNumero: 6,
    carrera: 'Licenciatura en Administración',
  },
  {
    id: '6LAD21',
    claveGrupo: '6LAD21',
    nombre: 'Grupo 6LAD21 - Vespertino',
    turno: 'Vespertino',
    horarioResumen: '14:00 a 20:00 hrs (Lun a Vie)',
    cupoDisponible: 25,
    cupoMaximo: 35,
    semestre: '6º Semestre',
    semestreNumero: 6,
    carrera: 'Licenciatura en Administración',
  },
  {
    id: '9LAD11',
    claveGrupo: '9LAD11',
    nombre: 'Grupo 9LAD11 - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 19,
    cupoMaximo: 35,
    semestre: '9º Semestre',
    semestreNumero: 9,
    carrera: 'Licenciatura en Administración',
  },
];

// Retícula Oficial Curricular TecNM / TESChi: Ingeniería en Sistemas Computacionales
export const ISC_CURRICULUM_COURSES: Course[] = [
  // --- SEMESTRE 1 ---
  {
    clave: 'ACF-0901',
    nombre: 'Cálculo Diferencial',
    creditos: 5,
    profesor: 'Mtro. José Luis Benítez',
    dias: 'Lun, Mié, Vie',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 101',
    semestre: 1,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'SCD-1008',
    nombre: 'Fundamentos de Programación',
    creditos: 5,
    profesor: 'Dr. Alan Turing',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Laboratorio L1',
    semestre: 1,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Programación',
  },
  {
    clave: 'ACA-0907',
    nombre: 'Taller de Ética',
    creditos: 4,
    profesor: 'Mtra. Claudia Morales',
    dias: 'Vie',
    horario: '11:00 - 14:00',
    aula: 'Edificio A - Aula 102',
    semestre: 1,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Sociales',
  },
  {
    clave: 'AEF-1041',
    nombre: 'Matemáticas Discretas',
    creditos: 5,
    profesor: 'Dra. Katherine Johnson',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 103',
    semestre: 1,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'ACC-0906',
    nombre: 'Fundamentos de Investigación',
    creditos: 4,
    profesor: 'Mtro. Roberto Flores',
    dias: 'Jue, Vie',
    horario: '14:00 - 16:00',
    aula: 'Edificio A - Aula 201',
    semestre: 1,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Metodología',
  },
  {
    clave: 'SCH-1024',
    nombre: 'Taller de Administración',
    creditos: 4,
    profesor: 'Mtra. Sandra Pérez',
    dias: 'Mar, Jue',
    horario: '11:00 - 13:00',
    aula: 'Edificio D - Aula 105',
    semestre: 1,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Gestión',
  },

  // --- SEMESTRE 2 ---
  {
    clave: 'ACF-0902',
    nombre: 'Cálculo Integral',
    creditos: 5,
    profesor: 'Dr. Fernando Navarro',
    dias: 'Lun, Mié, Vie',
    horario: '08:00 - 10:00',
    aula: 'Edificio B - Aula 204',
    semestre: 2,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'SCD-1020',
    nombre: 'Programación Orientada a Objetos',
    creditos: 5,
    profesor: 'Dr. James Gosling',
    dias: 'Mar, Jue',
    horario: '10:00 - 12:00',
    aula: 'Laboratorio L2',
    semestre: 2,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Programación',
  },
  {
    clave: 'ACF-0903',
    nombre: 'Álgebra Lineal',
    creditos: 5,
    profesor: 'Dra. Sofía Delgado',
    dias: 'Lun, Mié',
    horario: '10:00 - 12:00',
    aula: 'Edificio B - Aula 202',
    semestre: 2,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'AEC-1058',
    nombre: 'Química',
    creditos: 4,
    profesor: 'Dra. Marie Curie',
    dias: 'Mar, Jue',
    horario: '12:00 - 14:00',
    aula: 'Laboratorio Q1',
    semestre: 2,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'AEC-1053',
    nombre: 'Probabilidad y Estadística',
    creditos: 4,
    profesor: 'Mtro. Héctor Ramírez',
    dias: 'Lun, Vie',
    horario: '12:00 - 14:00',
    aula: 'Edificio C - Aula 103',
    semestre: 2,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'AEF-1031',
    nombre: 'Física General',
    creditos: 5,
    profesor: 'Dr. Richard Feynman',
    dias: 'Lun, Mié, Vie',
    horario: '14:00 - 16:00',
    aula: 'Edificio C - Aula 201',
    semestre: 2,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },

  // --- SEMESTRE 3 ---
  {
    clave: 'ACF-0904',
    nombre: 'Cálculo Vectorial',
    creditos: 5,
    profesor: 'Dr. Fernando Navarro',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 205',
    semestre: 3,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'AED-1026',
    nombre: 'Estructura de Datos',
    creditos: 5,
    profesor: 'Mtro. Linus Torvalds',
    dias: 'Lun, Mié',
    horario: '08:00 - 10:00',
    aula: 'Laboratorio L4',
    semestre: 3,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Programación',
  },
  {
    clave: 'AEC-1014',
    nombre: 'Cultura Empresarial',
    creditos: 4,
    profesor: 'Mtra. Sandra Pérez',
    dias: 'Vie',
    horario: '10:00 - 14:00',
    aula: 'Edificio D - Aula 202',
    semestre: 3,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Emprendimiento',
  },
  {
    clave: 'AEC-1061',
    nombre: 'Sistemas Operativos',
    creditos: 4,
    profesor: 'Dr. Ken Thompson',
    dias: 'Mar, Jue',
    horario: '09:00 - 11:00',
    aula: 'Laboratorio SO1',
    semestre: 3,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Sistemas',
  },
  {
    clave: 'SCC-1007',
    nombre: 'Física para Informática',
    creditos: 4,
    profesor: 'Dr. Carlos Mendoza',
    dias: 'Lun, Vie',
    horario: '10:00 - 12:00',
    aula: 'Edificio C - Aula 203',
    semestre: 3,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'ACD-0908',
    nombre: 'Desarrollo Sustentable',
    creditos: 5,
    profesor: 'Mtra. Gabriela Soto',
    dias: 'Lun, Mié',
    horario: '12:00 - 14:00',
    aula: 'Edificio A - Aula 302',
    semestre: 3,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ambiental',
  },

  // --- SEMESTRE 4 ---
  {
    clave: 'ACF-0905',
    nombre: 'Ecuaciones Diferenciales',
    creditos: 5,
    profesor: 'Mtro. José Luis Benítez',
    dias: 'Lun, Mié, Vie',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 301',
    semestre: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'SCC-1017',
    nombre: 'Métodos Numéricos',
    creditos: 4,
    profesor: 'Dra. Katherine Johnson',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Laboratorio L3',
    semestre: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias Básicas',
  },
  {
    clave: 'SCD-1027',
    nombre: 'Tópicos Avanzados de Programación',
    creditos: 5,
    profesor: 'Mtro. Linus Torvalds',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Laboratorio L4',
    semestre: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Programación',
  },
  {
    clave: 'SCA-1002',
    nombre: 'Fundamentos de Bases de Datos',
    creditos: 4,
    profesor: 'Dra. Grace Hopper',
    dias: 'Mar, Jue',
    horario: '09:00 - 11:00',
    aula: 'Laboratorio BD1',
    semestre: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Bases de Datos',
  },
  {
    clave: 'SCD-1022',
    nombre: 'Simulación',
    creditos: 5,
    profesor: 'Dr. John von Neumann',
    dias: 'Lun, Vie',
    horario: '11:00 - 13:00',
    aula: 'Edificio E - Aula 104',
    semestre: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Modelado',
  },
  {
    clave: 'SCD-1018',
    nombre: 'Principios Eléctricos y Aplicaciones Digitales',
    creditos: 5,
    profesor: 'Mtro. Armando Cruz',
    dias: 'Mar, Jue',
    horario: '11:00 - 13:00',
    aula: 'Laboratorio Electrónica E1',
    semestre: 4,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Hardware',
  },

  // --- SEMESTRE 5 ---
  {
    clave: 'SCB-1001',
    nombre: 'Administración de Bases de Datos',
    creditos: 5,
    profesor: 'Dra. Grace Hopper',
    dias: 'Lun, Mié',
    horario: '08:00 - 10:00',
    aula: 'Laboratorio BD1',
    semestre: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Bases de Datos',
  },
  {
    clave: 'SCD-1015',
    nombre: 'Lenguajes y Autómatas I',
    creditos: 5,
    profesor: 'Dr. Noam Chomsky',
    dias: 'Mar, Jue',
    horario: '08:00 - 10:00',
    aula: 'Edificio E - Aula 201',
    semestre: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias de la Computación',
  },
  {
    clave: 'SCD-1021',
    nombre: 'Redes de Computadoras',
    creditos: 5,
    profesor: 'Dr. Vint Cerf',
    dias: 'Lun, Vie',
    horario: '10:00 - 12:00',
    aula: 'Cisco Networking Lab',
    semestre: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Redes',
  },
  {
    clave: 'SCD-1003',
    nombre: 'Arquitectura de Computadoras',
    creditos: 5,
    profesor: 'Dr. Seymour Cray',
    dias: 'Mar, Jue',
    horario: '10:00 - 12:00',
    aula: 'Laboratorio Hardware H1',
    semestre: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Hardware',
  },
  {
    clave: 'SCC-1010',
    nombre: 'Graficación',
    creditos: 4,
    profesor: 'Mtro. John Carmack',
    dias: 'Mié, Vie',
    horario: '12:00 - 14:00',
    aula: 'Laboratorio Multimedia',
    semestre: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Gráficos',
  },
  {
    clave: 'SCD-1011',
    nombre: 'Fundamentos de Ingeniería de Software',
    creditos: 5,
    profesor: 'Dra. Margaret Hamilton',
    dias: 'Mar, Jue',
    horario: '12:00 - 14:00',
    aula: 'Edificio E - Aula 202',
    semestre: 5,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ingeniería de Software',
  },

  // --- SEMESTRE 6 ---
  {
    clave: 'SCD-1016',
    nombre: 'Lenguajes y Autómatas II',
    creditos: 5,
    profesor: 'Dr. Noam Chomsky',
    dias: 'Lun, Mié',
    horario: '07:00 - 09:00',
    aula: 'Edificio E - Aula 301',
    semestre: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Ciencias de la Computación',
  },
  {
    clave: 'SCD-1004',
    nombre: 'Conmutación y Enrutamiento en Redes',
    creditos: 5,
    profesor: 'Dr. Vint Cerf',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Cisco Networking Lab',
    semestre: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Redes',
  },
  {
    clave: 'SCD-1029',
    nombre: 'Taller de Sistemas Concurrentes',
    creditos: 5,
    profesor: 'Mtro. Rob Pike',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Laboratorio L5',
    semestre: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Sistemas',
  },
  {
    clave: 'SCD-1023',
    nombre: 'Sistemas Programables',
    creditos: 5,
    profesor: 'Mtro. Armando Cruz',
    dias: 'Mar, Jue',
    horario: '09:00 - 11:00',
    aula: 'Laboratorio Robótica',
    semestre: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Hardware',
  },
  {
    clave: 'SCC-1019',
    nombre: 'Programación Web',
    creditos: 4,
    profesor: 'Mtro. Tim Berners-Lee',
    dias: 'Vie',
    horario: '08:00 - 12:00',
    aula: 'Laboratorio Web1',
    semestre: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Desarrollo Web',
  },
  {
    clave: 'ACA-0909',
    nombre: 'Taller de Investigación I',
    creditos: 4,
    profesor: 'Dra. Elena Poniatowska',
    dias: 'Lun, Mié',
    horario: '11:00 - 13:00',
    aula: 'Edificio A - Aula 303',
    semestre: 6,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Investigación',
  },

  // --- SEMESTRE 7 ---
  {
    clave: 'ACA-0910',
    nombre: 'Taller de Investigación II',
    creditos: 4,
    profesor: 'Dra. Elena Poniatowska',
    dias: 'Lun, Mié',
    horario: '11:00 - 13:00',
    aula: 'Edificio A - Aula 303',
    semestre: 7,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Investigación',
  },
  {
    clave: 'SCD-1013',
    nombre: 'Inteligencia Artificial',
    creditos: 5,
    profesor: 'Dr. Marvin Minsky',
    dias: 'Mar, Jue',
    horario: '11:00 - 13:00',
    aula: 'Laboratorio IA',
    semestre: 7,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Inteligencia Artificial',
  },
  {
    clave: 'SCD-1002',
    nombre: 'Administración de Redes',
    creditos: 5,
    profesor: 'Dr. Vint Cerf',
    dias: 'Lun, Vie',
    horario: '13:00 - 15:00',
    aula: 'Cisco Networking Lab',
    semestre: 7,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Redes',
  },
  {
    clave: 'SCD-1025',
    nombre: 'Programación Móvil',
    creditos: 5,
    profesor: 'Mtro. Andy Rubin',
    dias: 'Mar, Jue',
    horario: '13:00 - 15:00',
    aula: 'Laboratorio Móvil',
    semestre: 7,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Móvil',
  },

  // --- SEMESTRE 8 ---
  {
    clave: 'ACA-0910',
    nombre: 'Taller de Investigación II',
    creditos: 4,
    profesor: 'Dra. Elena Poniatowska',
    dias: 'Lun, Mié',
    horario: '15:00 - 17:00',
    aula: 'Edificio A - Aula 303',
    semestre: 8,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Investigación',
  },
  {
    clave: 'SCD-1026',
    nombre: 'Sistemas Distribuidos',
    creditos: 5,
    profesor: 'Dr. Leslie Lamport',
    dias: 'Mar, Jue',
    horario: '15:00 - 17:00',
    aula: 'Laboratorio L5',
    semestre: 8,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Sistemas',
  },
  {
    clave: 'SCD-1028',
    nombre: 'Ciberseguridad Institucional',
    creditos: 5,
    profesor: 'Mtro. Kevin Mitnick',
    dias: 'Vie',
    horario: '14:00 - 18:00',
    aula: 'Cyber Security Operations Center',
    semestre: 8,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Seguridad',
  },

  // --- SEMESTRE 9 ---
  {
    clave: 'RES-0001',
    nombre: 'Residencia Profesional',
    creditos: 10,
    profesor: 'Comité de Residencias - Ciencias Básicas',
    dias: 'Lun a Vie',
    horario: 'Flexible (500 hrs)',
    aula: 'Empresa / Institución Receptora (TESChi)',
    semestre: 9,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Titulación',
  },
  {
    clave: 'SER-0001',
    nombre: 'Servicio Social',
    creditos: 10,
    profesor: 'Departamento de Servicio Social',
    dias: 'Lun a Vie',
    horario: 'Flexible (480 hrs)',
    aula: 'TESChi Campus Chimalhuacán',
    semestre: 9,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Titulación',
  },
  {
    clave: 'ACO-0001',
    nombre: 'Actividades Complementarias',
    creditos: 5,
    profesor: 'Departamento de Servicios Escolares',
    dias: 'Lun a Vie',
    horario: 'Flexible',
    aula: 'TESChi Campus Chimalhuacán',
    semestre: 9,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Complementaria',
  },
  {
    clave: 'OPT-0901',
    nombre: 'Especialidad I: Arquitectura y Ciberseguridad Cloud',
    creditos: 5,
    profesor: 'Mtro. Kevin Mitnick',
    dias: 'Mar, Jue',
    horario: '16:00 - 18:00',
    aula: 'Laboratorio Cloud & DevOps',
    semestre: 9,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Especialidad',
  },
  {
    clave: 'OPT-0902',
    nombre: 'Especialidad II: Inteligencia Artificial Aplicada',
    creditos: 5,
    profesor: 'Dr. Geoffrey Hinton',
    dias: 'Lun, Mié',
    horario: '16:00 - 18:00',
    aula: 'Laboratorio IA',
    semestre: 9,
    carrera: 'Ingeniería en Sistemas Computacionales',
    area: 'Especialidad',
  },
];

// Retícula Oficial Curricular TecNM / TESChi: Licenciatura en Administración (Plan LADM-2010-234)
export const LAD_CURRICULUM_COURSES: Course[] = [
  // --- SEMESTRE 1 ---
  {
    clave: 'ADF-1025',
    nombre: 'Teoría General de la Administración',
    creditos: 5,
    profesor: 'Mtro. Peter Drucker',
    dias: 'Lun, Mié, Vie',
    horario: '07:00 - 09:00',
    aula: 'Edificio C - Aula 101',
    semestre: 1,
    carrera: 'Licenciatura en Administración',
    area: 'Ciencias de la Administración',
  },
  {
    clave: 'ACA-0907',
    nombre: 'Taller de Ética',
    creditos: 4,
    profesor: 'Mtra. Simone de Beauvoir',
    dias: 'Vie',
    horario: '09:00 - 13:00',
    aula: 'Edificio A - Aula 102',
    semestre: 1,
    carrera: 'Licenciatura en Administración',
    area: 'Ciencias Sociales',
  },
  {
    clave: 'ACC-0906',
    nombre: 'Fundamentos de Investigación',
    creditos: 4,
    profesor: 'Dr. Mario Bunge',
    dias: 'Jue, Vie',
    horario: '14:00 - 16:00',
    aula: 'Edificio A - Aula 201',
    semestre: 1,
    carrera: 'Licenciatura en Administración',
    area: 'Metodología',
  },
  {
    clave: 'LAD-1017',
    nombre: 'Matemáticas Aplicadas a la Administración',
    creditos: 5,
    profesor: 'Dra. Katherine Johnson',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 103',
    semestre: 1,
    carrera: 'Licenciatura en Administración',
    area: 'Métodos Cuantitativos',
  },
  {
    clave: 'ADH-1010',
    nombre: 'Contabilidad Financiera',
    creditos: 4,
    profesor: 'Mtro. Luca Pacioli',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 102',
    semestre: 1,
    carrera: 'Licenciatura en Administración',
    area: 'Finanzas y Contabilidad',
  },
  {
    clave: 'ACD-0908',
    nombre: 'Desarrollo Humano',
    creditos: 5,
    profesor: 'Mtra. Carl Rogers',
    dias: 'Mar, Jue',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 103',
    semestre: 1,
    carrera: 'Licenciatura en Administración',
    area: 'Capital Humano',
  },

  // --- SEMESTRE 2 ---
  {
    clave: 'ADF-1011',
    nombre: 'Función Administrativa I',
    creditos: 5,
    profesor: 'Mtro. Henri Fayol',
    dias: 'Lun, Mié, Vie',
    horario: '08:00 - 10:00',
    aula: 'Edificio C - Aula 201',
    semestre: 2,
    carrera: 'Licenciatura en Administración',
    area: 'Ciencias de la Administración',
  },
  {
    clave: 'LAD-1020',
    nombre: 'Matemáticas Financieras',
    creditos: 5,
    profesor: 'Dr. Fernando Navarro',
    dias: 'Mar, Jue',
    horario: '08:00 - 10:00',
    aula: 'Edificio B - Aula 204',
    semestre: 2,
    carrera: 'Licenciatura en Administración',
    area: 'Finanzas y Contabilidad',
  },
  {
    clave: 'ADH-1011',
    nombre: 'Contabilidad de Costos',
    creditos: 4,
    profesor: 'Mtra. Sandra Pérez',
    dias: 'Lun, Mié',
    horario: '10:00 - 12:00',
    aula: 'Edificio C - Aula 202',
    semestre: 2,
    carrera: 'Licenciatura en Administración',
    area: 'Finanzas y Contabilidad',
  },
  {
    clave: 'LAD-1007',
    nombre: 'Dinámica Social',
    creditos: 5,
    profesor: 'Dr. Max Weber',
    dias: 'Mar, Jue',
    horario: '10:00 - 12:00',
    aula: 'Edificio C - Aula 203',
    semestre: 2,
    carrera: 'Licenciatura en Administración',
    area: 'Ciencias Sociales',
  },
  {
    clave: 'LAD-1016',
    nombre: 'Legislación Comercial',
    creditos: 5,
    profesor: 'Lic. Eduardo García',
    dias: 'Vie',
    horario: '08:00 - 12:00',
    aula: 'Edificio C - Aula 204',
    semestre: 2,
    carrera: 'Licenciatura en Administración',
    area: 'Marco Jurídico',
  },
  {
    clave: 'LAD-1015',
    nombre: 'Informática para la Administración',
    creditos: 5,
    profesor: 'Ing. Ada Lovelace',
    dias: 'Lun, Mié',
    horario: '12:00 - 14:00',
    aula: 'Laboratorio de Cómputo C1',
    semestre: 2,
    carrera: 'Licenciatura en Administración',
    area: 'Tecnologías de Información',
  },

  // --- SEMESTRE 3 ---
  {
    clave: 'ADF-1012',
    nombre: 'Función Administrativa II',
    creditos: 5,
    profesor: 'Mtro. Henri Fayol',
    dias: 'Lun, Mié',
    horario: '07:00 - 09:00',
    aula: 'Edificio C - Aula 301',
    semestre: 3,
    carrera: 'Licenciatura en Administración',
    area: 'Ciencias de la Administración',
  },
  {
    clave: 'AEF-1024',
    nombre: 'Estadística Aplicada I',
    creditos: 5,
    profesor: 'Dr. Karl Pearson',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 302',
    semestre: 3,
    carrera: 'Licenciatura en Administración',
    area: 'Métodos Cuantitativos',
  },
  {
    clave: 'ADH-1012',
    nombre: 'Contabilidad Gerencial',
    creditos: 4,
    profesor: 'Mtro. Luca Pacioli',
    dias: 'Vie',
    horario: '07:00 - 11:00',
    aula: 'Edificio C - Aula 302',
    semestre: 3,
    carrera: 'Licenciatura en Administración',
    area: 'Finanzas y Contabilidad',
  },
  {
    clave: 'LAD-1008',
    nombre: 'Economía Empresarial',
    creditos: 5,
    profesor: 'Dr. John Maynard Keynes',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 303',
    semestre: 3,
    carrera: 'Licenciatura en Administración',
    area: 'Economía',
  },
  {
    clave: 'LAD-1019',
    nombre: 'Marco Legal de las Organizaciones',
    creditos: 5,
    profesor: 'Lic. Eduardo García',
    dias: 'Mar, Jue',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 304',
    semestre: 3,
    carrera: 'Licenciatura en Administración',
    area: 'Marco Jurídico',
  },
  {
    clave: 'LAD-1004',
    nombre: 'Comportamiento Organizacional',
    creditos: 5,
    profesor: 'Mtra. Elton Mayo',
    dias: 'Mié, Vie',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 305',
    semestre: 3,
    carrera: 'Licenciatura en Administración',
    area: 'Capital Humano',
  },

  // --- SEMESTRE 4 ---
  {
    clave: 'ADF-1013',
    nombre: 'Gestión Estratégica del Capital Humano I',
    creditos: 5,
    profesor: 'Mtro. Idalberto Chiavenato',
    dias: 'Lun, Mié, Vie',
    horario: '07:00 - 09:00',
    aula: 'Edificio C - Aula 401',
    semestre: 4,
    carrera: 'Licenciatura en Administración',
    area: 'Capital Humano',
  },
  {
    clave: 'AEF-1025',
    nombre: 'Estadística Aplicada II',
    creditos: 5,
    profesor: 'Dr. Ronald Fisher',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 402',
    semestre: 4,
    carrera: 'Licenciatura en Administración',
    area: 'Métodos Cuantitativos',
  },
  {
    clave: 'LAD-1018',
    nombre: 'Métodos Cuantitativos de Gestión',
    creditos: 5,
    profesor: 'Dr. George Dantzig',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 402',
    semestre: 4,
    carrera: 'Licenciatura en Administración',
    area: 'Investigación de Operaciones',
  },
  {
    clave: 'LAD-1010',
    nombre: 'Macroeconomía',
    creditos: 5,
    profesor: 'Dr. Milton Friedman',
    dias: 'Mar, Jue',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 403',
    semestre: 4,
    carrera: 'Licenciatura en Administración',
    area: 'Economía',
  },
  {
    clave: 'ADF-1021',
    nombre: 'Procesos Estructurales',
    creditos: 5,
    profesor: 'Mtra. Mary Parker Follett',
    dias: 'Lun, Vie',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 404',
    semestre: 4,
    carrera: 'Licenciatura en Administración',
    area: 'Ciencias de la Administración',
  },
  {
    clave: 'LAD-1006',
    nombre: 'Fundamentos de Mercadotecnia',
    creditos: 5,
    profesor: 'Dr. Philip Kotler',
    dias: 'Mar, Jue',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 405',
    semestre: 4,
    carrera: 'Licenciatura en Administración',
    area: 'Mercadotecnia',
  },

  // --- SEMESTRE 5 ---
  {
    clave: 'ADF-1014',
    nombre: 'Gestión Estratégica del Capital Humano II',
    creditos: 5,
    profesor: 'Mtro. Idalberto Chiavenato',
    dias: 'Lun, Mié',
    horario: '07:00 - 09:00',
    aula: 'Edificio C - Aula 501',
    semestre: 5,
    carrera: 'Licenciatura en Administración',
    area: 'Capital Humano',
  },
  {
    clave: 'ADF-1001',
    nombre: 'Administración de la Calidad',
    creditos: 5,
    profesor: 'Dr. W. Edwards Deming',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Edificio C - Aula 502',
    semestre: 5,
    carrera: 'Licenciatura en Administración',
    area: 'Calidad y Productividad',
  },
  {
    clave: 'ADF-1017',
    nombre: 'Gestión Financiera',
    creditos: 5,
    profesor: 'Dra. Merton Miller',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 503',
    semestre: 5,
    carrera: 'Licenciatura en Administración',
    area: 'Finanzas y Contabilidad',
  },
  {
    clave: 'ADF-1019',
    nombre: 'Mezcla de Mercadotecnia',
    creditos: 5,
    profesor: 'Dr. Philip Kotler',
    dias: 'Mar, Jue',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 504',
    semestre: 5,
    carrera: 'Licenciatura en Administración',
    area: 'Mercadotecnia',
  },
  {
    clave: 'LAD-1009',
    nombre: 'Innovación y Emprendedurismo',
    creditos: 5,
    profesor: 'Mtro. Joseph Schumpeter',
    dias: 'Vie',
    horario: '08:00 - 12:00',
    aula: 'Incubadora de Empresas TESChi',
    semestre: 5,
    carrera: 'Licenciatura en Administración',
    area: 'Emprendimiento',
  },
  {
    clave: 'LAD-1014',
    nombre: 'Higiene y Seguridad Ocupacional',
    creditos: 5,
    profesor: 'Mtra. Sandra Pérez',
    dias: 'Lun, Mié',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 505',
    semestre: 5,
    carrera: 'Licenciatura en Administración',
    area: 'Capital Humano',
  },

  // --- SEMESTRE 6 ---
  {
    clave: 'ADF-1008',
    nombre: 'Diagnóstico y Evaluación Empresarial',
    creditos: 5,
    profesor: 'Mtro. Michael Porter',
    dias: 'Lun, Mié',
    horario: '07:00 - 09:00',
    aula: 'Edificio C - Aula 601',
    semestre: 6,
    carrera: 'Licenciatura en Administración',
    area: 'Estrategia Empresarial',
  },
  {
    clave: 'ADF-1018',
    nombre: 'Métodos de Pronósticos en los Negocios',
    creditos: 5,
    profesor: 'Dr. Ronald Fisher',
    dias: 'Mar, Jue',
    horario: '07:00 - 09:00',
    aula: 'Edificio B - Aula 602',
    semestre: 6,
    carrera: 'Licenciatura en Administración',
    area: 'Métodos Cuantitativos',
  },
  {
    clave: 'ADF-1022',
    nombre: 'Sistemas de Información de Mercadotecnia',
    creditos: 5,
    profesor: 'Dra. Shoshana Zuboff',
    dias: 'Lun, Mié',
    horario: '09:00 - 11:00',
    aula: 'Laboratorio de Negocios N1',
    semestre: 6,
    carrera: 'Licenciatura en Administración',
    area: 'Mercadotecnia',
  },
  {
    clave: 'ADF-1024',
    nombre: 'Taller de Consultoría Estratégica',
    creditos: 5,
    profesor: 'Mtro. Peter Drucker',
    dias: 'Mar, Jue',
    horario: '09:00 - 11:00',
    aula: 'Edificio C - Aula 603',
    semestre: 6,
    carrera: 'Licenciatura en Administración',
    area: 'Consultoría',
  },
  {
    clave: 'ACA-0909',
    nombre: 'Taller de Investigación I',
    creditos: 4,
    profesor: 'Dra. Elena Poniatowska',
    dias: 'Vie',
    horario: '08:00 - 12:00',
    aula: 'Edificio A - Aula 303',
    semestre: 6,
    carrera: 'Licenciatura en Administración',
    area: 'Investigación',
  },
  {
    clave: 'LAD-1003',
    nombre: 'Comercio Internacional',
    creditos: 5,
    profesor: 'Dr. David Ricardo',
    dias: 'Lun, Mié',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 604',
    semestre: 6,
    carrera: 'Licenciatura en Administración',
    area: 'Negocios Internacionales',
  },

  // --- SEMESTRE 7 ---
  {
    clave: 'ADF-1004',
    nombre: 'Administración Estratégica',
    creditos: 5,
    profesor: 'Mtro. Michael Porter',
    dias: 'Lun, Mié',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 701',
    semestre: 7,
    carrera: 'Licenciatura en Administración',
    area: 'Estrategia Empresarial',
  },
  {
    clave: 'ADF-1009',
    nombre: 'Formulación y Evaluación de Proyectos',
    creditos: 5,
    profesor: 'Dr. Gabriel Baca Urbina',
    dias: 'Mar, Jue',
    horario: '11:00 - 13:00',
    aula: 'Edificio C - Aula 702',
    semestre: 7,
    carrera: 'Licenciatura en Administración',
    area: 'Proyectos de Inversión',
  },
  {
    clave: 'ACA-0910',
    nombre: 'Taller de Investigación II',
    creditos: 4,
    profesor: 'Dra. Elena Poniatowska',
    dias: 'Vie',
    horario: '12:00 - 16:00',
    aula: 'Edificio A - Aula 303',
    semestre: 7,
    carrera: 'Licenciatura en Administración',
    area: 'Investigación',
  },
  {
    clave: 'LAD-1005',
    nombre: 'Comunicación Organizacional',
    creditos: 5,
    profesor: 'Mtra. Paul Watzlawick',
    dias: 'Lun, Mié',
    horario: '13:00 - 15:00',
    aula: 'Edificio C - Aula 703',
    semestre: 7,
    carrera: 'Licenciatura en Administración',
    area: 'Capital Humano',
  },
  {
    clave: 'LAD-1021',
    nombre: 'Mercadotecnia Digital y Redes',
    creditos: 5,
    profesor: 'Dr. Philip Kotler',
    dias: 'Mar, Jue',
    horario: '13:00 - 15:00',
    aula: 'Laboratorio de Negocios N1',
    semestre: 7,
    carrera: 'Licenciatura en Administración',
    area: 'Mercadotecnia',
  },

  // --- SEMESTRE 8 ---
  {
    clave: 'ADF-1020',
    nombre: 'Plan de Negocios y Franquicias',
    creditos: 5,
    profesor: 'Mtro. Joseph Schumpeter',
    dias: 'Lun, Mié',
    horario: '15:00 - 17:00',
    aula: 'Incubadora de Empresas TESChi',
    semestre: 8,
    carrera: 'Licenciatura en Administración',
    area: 'Emprendimiento',
  },
  {
    clave: 'LAD-1011',
    nombre: 'Liderazgo Estratégico y Negociación',
    creditos: 5,
    profesor: 'Mtro. William Ury',
    dias: 'Mar, Jue',
    horario: '15:00 - 17:00',
    aula: 'Edificio C - Aula 801',
    semestre: 8,
    carrera: 'Licenciatura en Administración',
    area: 'Habilidades Directivas',
  },
  {
    clave: 'LAD-1012',
    nombre: 'Auditoría Administrativa',
    creditos: 5,
    profesor: 'Mtra. Sandra Pérez',
    dias: 'Vie',
    horario: '14:00 - 18:00',
    aula: 'Edificio C - Aula 802',
    semestre: 8,
    carrera: 'Licenciatura en Administración',
    area: 'Control y Auditoría',
  },
  {
    clave: 'LAD-1013',
    nombre: 'Finanzas Corporativas Avanzadas',
    creditos: 5,
    profesor: 'Dr. Merton Miller',
    dias: 'Lun, Mié',
    horario: '17:00 - 19:00',
    aula: 'Edificio C - Aula 803',
    semestre: 8,
    carrera: 'Licenciatura en Administración',
    area: 'Finanzas y Contabilidad',
  },

  // --- SEMESTRE 9 ---
  {
    clave: 'RES-0001',
    nombre: 'Residencia Profesional',
    creditos: 10,
    profesor: 'Comité de Residencias - Ciencias Económico Administrativas',
    dias: 'Lun a Vie',
    horario: 'Flexible (500 hrs)',
    aula: 'Empresa / Institución Receptora (TESChi)',
    semestre: 9,
    carrera: 'Licenciatura en Administración',
    area: 'Titulación',
  },
  {
    clave: 'SER-0001',
    nombre: 'Servicio Social',
    creditos: 10,
    profesor: 'Departamento de Servicio Social',
    dias: 'Lun a Vie',
    horario: 'Flexible (480 hrs)',
    aula: 'TESChi Campus Chimalhuacán',
    semestre: 9,
    carrera: 'Licenciatura en Administración',
    area: 'Titulación',
  },
  {
    clave: 'ACO-0001',
    nombre: 'Actividades Complementarias',
    creditos: 5,
    profesor: 'Departamento de Servicios Escolares',
    dias: 'Lun a Vie',
    horario: 'Flexible',
    aula: 'TESChi Campus Chimalhuacán',
    semestre: 9,
    carrera: 'Licenciatura en Administración',
    area: 'Complementaria',
  },
  {
    clave: 'OPT-0921',
    nombre: 'Especialidad I: Gestión y Desarrollo del Talento Humano',
    creditos: 5,
    profesor: 'Mtro. Idalberto Chiavenato',
    dias: 'Mar, Jue',
    horario: '16:00 - 18:00',
    aula: 'Edificio C - Aula 901',
    semestre: 9,
    carrera: 'Licenciatura en Administración',
    area: 'Especialidad',
  },
  {
    clave: 'OPT-0922',
    nombre: 'Especialidad II: Dirección y Finanzas Estratégicas',
    creditos: 5,
    profesor: 'Dr. Merton Miller',
    dias: 'Lun, Mié',
    horario: '16:00 - 18:00',
    aula: 'Edificio C - Aula 902',
    semestre: 9,
    carrera: 'Licenciatura en Administración',
    area: 'Especialidad',
  },
];

export const ALL_CURRICULUM_COURSES: Course[] = [
  ...ISC_CURRICULUM_COURSES,
  ...LAD_CURRICULUM_COURSES,
];

// Por defecto, las materias de selección de carga corresponden a la oferta curricular de la carrera
export const AVAILABLE_COURSES: Course[] = ISC_CURRICULUM_COURSES.filter(
  (c) => c.semestre === 6
);

export const KARDEX_HISTORY: SemesterRecord[] = [
  {
    id: 'sem-1',
    semestreTitulo: '1º Semestre',
    periodoNombre: 'Septiembre 2022 - Enero 2023 • 6 Materias',
    numMaterias: 6,
    enCurso: false,
    promedioSemestral: 9.5,
    materias: [
      {
        clave: 'ACF-0901',
        nombre: 'Cálculo Diferencial',
        creditos: 5,
        profesor: 'Mtro. José Luis Benítez',
        dias: 'Lun, Mié, Vie',
        horario: '07:00 - 09:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.5,
      },
      {
        clave: 'SCD-1008',
        nombre: 'Fundamentos de Programación',
        creditos: 5,
        profesor: 'Dr. Alan Turing',
        dias: 'Lun, Mié',
        horario: '09:00 - 11:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 10.0,
      },
      {
        clave: 'ACA-0907',
        nombre: 'Taller de Ética',
        creditos: 4,
        profesor: 'Mtra. Simone de Beauvoir',
        dias: 'Vie',
        horario: '07:00 - 11:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.8,
      },
      {
        clave: 'AEF-1041',
        nombre: 'Matemáticas Discretas',
        creditos: 5,
        profesor: 'Dr. John von Neumann',
        dias: 'Mar, Jue',
        horario: '07:00 - 09:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.2,
      },
      {
        clave: 'SCH-1024',
        nombre: 'Taller de Administración',
        creditos: 4,
        profesor: 'Mtro. Peter Drucker',
        dias: 'Mar, Jue',
        horario: '09:00 - 11:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.0,
      },
      {
        clave: 'ACC-0906',
        nombre: 'Fundamentos de Investigación',
        creditos: 4,
        profesor: 'Dr. Mario Bunge',
        dias: 'Vie',
        horario: '11:00 - 15:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.5,
      },
    ],
  },
  {
    id: 'sem-2',
    semestreTitulo: '2º Semestre',
    periodoNombre: 'Febrero - Julio 2023 • 6 Materias',
    numMaterias: 6,
    enCurso: false,
    promedioSemestral: 9.6,
    materias: [
      {
        clave: 'ACF-0902',
        nombre: 'Cálculo Integral',
        creditos: 5,
        profesor: 'Dr. Fernando Navarro',
        dias: 'Lun, Mié, Vie',
        horario: '08:00 - 10:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.4,
      },
      {
        clave: 'SCD-1020',
        nombre: 'Programación Orientada a Objetos',
        creditos: 5,
        profesor: 'Dr. James Gosling',
        dias: 'Mar, Jue',
        horario: '10:00 - 12:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.8,
      },
      {
        clave: 'ACF-0903',
        nombre: 'Álgebra Lineal',
        creditos: 5,
        profesor: 'Dra. Sofía Delgado',
        dias: 'Lun, Mié',
        horario: '10:00 - 12:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.2,
      },
      {
        clave: 'AEC-1058',
        nombre: 'Química',
        creditos: 4,
        profesor: 'Dra. Marie Curie',
        dias: 'Mar, Jue',
        horario: '12:00 - 14:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.5,
      },
      {
        clave: 'AEC-1053',
        nombre: 'Probabilidad y Estadística',
        creditos: 4,
        profesor: 'Mtro. Héctor Ramírez',
        dias: 'Lun, Vie',
        horario: '12:00 - 14:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.7,
      },
      {
        clave: 'AEF-1031',
        nombre: 'Física General',
        creditos: 5,
        profesor: 'Dr. Richard Feynman',
        dias: 'Mié, Vie',
        horario: '14:00 - 16:30',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.6,
      },
    ],
  },
  {
    id: 'sem-3',
    semestreTitulo: '3º Semestre',
    periodoNombre: 'Septiembre 2023 - Enero 2024 • 6 Materias',
    numMaterias: 6,
    enCurso: false,
    promedioSemestral: 9.5,
    materias: [
      {
        clave: 'ACF-0904',
        nombre: 'Cálculo Vectorial',
        creditos: 5,
        profesor: 'Dr. Fernando Navarro',
        dias: 'Lun, Mié, Vie',
        horario: '07:00 - 09:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.3,
      },
      {
        clave: 'SCD-1007',
        nombre: 'Estructura de Datos',
        creditos: 5,
        profesor: 'Dra. Ada Lovelace',
        dias: 'Mar, Jue',
        horario: '07:00 - 09:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.9,
      },
      {
        clave: 'SCC-1005',
        nombre: 'Cultura Empresarial',
        creditos: 4,
        profesor: 'Mtro. Peter Drucker',
        dias: 'Lun, Mié',
        horario: '09:00 - 11:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.4,
      },
      {
        clave: 'SCC-1013',
        nombre: 'Investigación de Operaciones',
        creditos: 4,
        profesor: 'Dr. George Dantzig',
        dias: 'Mar, Jue',
        horario: '09:00 - 11:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.2,
      },
      {
        clave: 'SCD-1022',
        nombre: 'Sistemas Electrónicos para Informática',
        creditos: 5,
        profesor: 'Dr. Claude Shannon',
        dias: 'Vie',
        horario: '07:00 - 12:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.6,
      },
      {
        clave: 'SCD-1015',
        nombre: 'Lenguajes y Autómatas I',
        creditos: 5,
        profesor: 'Dr. Noam Chomsky',
        dias: 'Lun, Mié',
        horario: '11:00 - 13:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.8,
      },
    ],
  },
];

export const INITIAL_COMPROBANTE: ComprobanteRecord = {
  id: 'COMP-2026-001',
  folio: 'FOR-002-01/02/TESCHI-2026-9ISC',
  fechaEmision: '23/09/2026',
  tipo: 'reinscripcion',
  matricula: '2022452139',
  nombreAlumno: 'Gálvez Romero, Irvin Osvaldo',
  carrera: 'Ingeniería en Sistemas Computacionales',
  semestreSolicitado: 'NOVENO',
  grupo: '9ISC11',
  totalCreditos: 35,
  hashFirmaDigital: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  esOficial: true,
  materias: [
    {
      clave: 'RES-0001',
      nombre: 'Residencia Profesional',
      creditos: 10,
      profesor: 'Comité de Residencias - Ciencias Básicas',
      dias: 'Lun a Vie',
      horario: 'Flexible (500 hrs)',
    },
    {
      clave: 'SER-0001',
      nombre: 'Servicio Social',
      creditos: 10,
      profesor: 'Departamento de Servicio Social',
      dias: 'Lun a Vie',
      horario: 'Flexible (480 hrs)',
    },
    {
      clave: 'ACO-0001',
      nombre: 'Actividades Complementarias',
      creditos: 5,
      profesor: 'Departamento de Servicios Escolares',
      dias: 'Lun a Vie',
      horario: 'Flexible',
    },
    {
      clave: 'OPT-0901',
      nombre: 'Especialidad I: Arquitectura y Ciberseguridad Cloud',
      creditos: 5,
      profesor: 'Mtro. Kevin Mitnick',
      dias: 'Mar, Jue',
      horario: '16:00 - 18:00',
    },
    {
      clave: 'OPT-0902',
      nombre: 'Especialidad II: Inteligencia Artificial Aplicada',
      creditos: 5,
      profesor: 'Dr. Geoffrey Hinton',
      dias: 'Lun, Mié',
      horario: '16:00 - 18:00',
    },
  ],
};
