import { StudentProfile, GroupOption, Course, SemesterRecord, ComprobanteRecord } from '../types';

export const INITIAL_STUDENT: StudentProfile = {
  matricula: '201912345',
  nombre: 'García López, Juan Carlos',
  nombreCorto: 'Alejandro Ruiz',
  carrera: 'Ingeniería en Sistemas Computacionales',
  periodoActual: 'Septiembre - Enero 2026-2027',
  semestreActual: 'Noveno Semestre',
  promedioGeneral: 9.2,
  creditosAcumulados: 240,
  creditosTotales: 350,
  avancePorcentaje: 68,
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  email: 'jgarcia.isc@teschi.edu.mx',
  status: 'regular',
  biometricsRegistered: false,
};

export const AVAILABLE_GROUPS: GroupOption[] = [
  {
    id: '4A',
    nombre: 'Grupo 4A - Matutino',
    turno: 'Matutino',
    horarioResumen: '07:00 a 13:00 hrs (Lun a Vie)',
    cupoDisponible: 8,
    cupoMaximo: 35,
    semestre: '4º Semestre',
  },
  {
    id: '4B',
    nombre: 'Grupo 4B - Matutino',
    turno: 'Matutino',
    horarioResumen: '08:00 a 14:00 hrs (Lun a Vie)',
    cupoDisponible: 14,
    cupoMaximo: 35,
    semestre: '4º Semestre',
  },
  {
    id: '4C',
    nombre: 'Grupo 4C - Vespertino',
    turno: 'Vespertino',
    horarioResumen: '14:00 a 20:00 hrs (Lun a Vie)',
    cupoDisponible: 21,
    cupoMaximo: 35,
    semestre: '4º Semestre',
  },
];

export const AVAILABLE_COURSES: Course[] = [
  {
    clave: 'INF-101',
    nombre: 'Programación Básica',
    creditos: 5,
    profesor: 'Dr. Alan Turing',
    dias: 'Lun, Mié, Vie',
    horario: '08:00 - 10:00',
    aula: 'Laboratorio L1',
  },
  {
    clave: 'MAT-201',
    nombre: 'Cálculo Integral',
    creditos: 4,
    profesor: 'Dra. Katherine Johnson',
    dias: 'Mar, Jue',
    horario: '10:00 - 12:00',
    aula: 'Edificio B - Aula 204',
  },
  {
    clave: 'FIS-305',
    nombre: 'Física Cuántica',
    creditos: 6,
    profesor: 'Dr. Richard Feynman',
    dias: 'Lun, Mar, Mié',
    horario: '14:00 - 16:00',
    aula: 'Edificio C - Aula 301',
  },
  {
    clave: 'ING-102',
    nombre: 'Inglés Académico I',
    creditos: 4,
    profesor: 'Prof. Jane Doe',
    dias: 'Jue, Vie',
    horario: '16:00 - 18:00',
    aula: 'Centro de Idiomas A3',
  },
  {
    clave: 'IS101',
    nombre: 'Programación Avanzada',
    creditos: 8,
    profesor: 'Mtro. Linus Torvalds',
    dias: 'Lun, Mié',
    horario: '10:00 - 12:00',
    aula: 'Laboratorio L4',
  },
  {
    clave: 'DB201',
    nombre: 'Bases de Datos Distribuidas',
    creditos: 6,
    profesor: 'Dra. Grace Hopper',
    dias: 'Mar, Jue',
    horario: '08:00 - 10:00',
    aula: 'Laboratorio BD1',
  },
  {
    clave: 'NT301',
    nombre: 'Redes de Computadoras II',
    creditos: 8,
    profesor: 'Dr. Vint Cerf',
    dias: 'Lun, Vie',
    horario: '12:00 - 14:00',
    aula: 'Cisco Networking Lab',
  },
  {
    clave: 'SE401',
    nombre: 'Ingeniería de Software',
    creditos: 6,
    profesor: 'Dra. Margaret Hamilton',
    dias: 'Mar, Jue',
    horario: '14:00 - 16:00',
    aula: 'Edificio E - Aula 102',
  },
  {
    clave: 'HU102',
    nombre: 'Ética Profesional',
    creditos: 4,
    profesor: 'Mtro. Roberto Flores',
    dias: 'Vie',
    horario: '10:00 - 14:00',
    aula: 'Edificio A - Aula 105',
  },
];

export const KARDEX_HISTORY: SemesterRecord[] = [
  {
    id: 'sem-1',
    semestreTitulo: '1º Semestre',
    periodoNombre: 'Otoño 2021 • 5 Materias',
    numMaterias: 5,
    enCurso: false,
    promedioSemestral: 9.3,
    materias: [
      {
        clave: 'CS101',
        nombre: 'Introducción a la Programación',
        creditos: 8,
        profesor: 'Dr. Alan Turing',
        dias: 'Lun, Mié',
        horario: '07:00 - 09:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.5,
      },
      {
        clave: 'MA102',
        nombre: 'Matemáticas Discretas',
        creditos: 8,
        profesor: 'Dra. Katherine Johnson',
        dias: 'Mar, Jue',
        horario: '09:00 - 11:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 8.8,
      },
      {
        clave: 'PH101',
        nombre: 'Física Universitaria I',
        creditos: 10,
        profesor: 'Dr. Richard Feynman',
        dias: 'Lun, Mar, Mié',
        horario: '11:00 - 13:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.0,
      },
      {
        clave: 'CH101',
        nombre: 'Química General',
        creditos: 8,
        profesor: 'Dra. Marie Curie',
        dias: 'Mar, Jue',
        horario: '13:00 - 15:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.2,
      },
      {
        clave: 'ET101',
        nombre: 'Taller de Ética',
        creditos: 4,
        profesor: 'Mtro. Roberto Flores',
        dias: 'Vie',
        horario: '08:00 - 12:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 10.0,
      },
    ],
  },
  {
    id: 'sem-2',
    semestreTitulo: '2º Semestre',
    periodoNombre: 'Primavera 2022 • 5 Materias',
    numMaterias: 5,
    enCurso: false,
    promedioSemestral: 9.2,
    materias: [
      {
        clave: 'CS102',
        nombre: 'Estructuras de Datos y Algoritmos',
        creditos: 8,
        profesor: 'Dra. Ada Lovelace',
        dias: 'Lun, Mié',
        horario: '08:00 - 10:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.4,
      },
      {
        clave: 'MA201',
        nombre: 'Cálculo Diferencial e Integral',
        creditos: 8,
        profesor: 'Dr. Carl Gauss',
        dias: 'Mar, Jue',
        horario: '10:00 - 12:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 8.9,
      },
      {
        clave: 'PH102',
        nombre: 'Electricidad y Magnetismo',
        creditos: 8,
        profesor: 'Dr. Nikola Tesla',
        dias: 'Vie',
        horario: '08:00 - 12:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.1,
      },
      {
        clave: 'AD101',
        nombre: 'Administración y Gestión',
        creditos: 6,
        profesor: 'Lic. Martha Ramos',
        dias: 'Lun, Mié',
        horario: '12:00 - 14:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.6,
      },
      {
        clave: 'IN101',
        nombre: 'Inglés Técnico Profesional',
        creditos: 4,
        profesor: 'Prof. Jane Doe',
        dias: 'Jue',
        horario: '14:00 - 18:00',
        tipoEvaluacion: 'Ordinario',
        calificacion: 9.8,
      },
    ],
  },
  {
    id: 'sem-3',
    semestreTitulo: '3º Semestre en Curso',
    periodoNombre: 'Periodo 2024-1 • En Evaluación',
    numMaterias: 5,
    enCurso: true,
    materias: [],
  },
];

export const INITIAL_COMPROBANTE: ComprobanteRecord = {
  id: 'COMP-2024-001',
  folio: 'FOR-002-01/02/19JUN25',
  fechaEmision: '29/08/2024',
  tipo: 'reinscripcion',
  matricula: '201912345',
  nombreAlumno: 'García López, Juan Carlos',
  carrera: 'Ingeniería en Sistemas',
  semestreSolicitado: 'NOVENO',
  grupo: '4A',
  totalCreditos: 32,
  hashFirmaDigital: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  esOficial: true,
  materias: [
    {
      clave: 'IS101',
      nombre: 'Programación Avanzada',
      creditos: 8,
      profesor: 'Mtro. Linus Torvalds',
      dias: 'Lun, Mié',
      horario: '10:00 - 12:00',
    },
    {
      clave: 'DB201',
      nombre: 'Bases de Datos Distribuidas',
      creditos: 6,
      profesor: 'Dra. Grace Hopper',
      dias: 'Mar, Jue',
      horario: '08:00 - 10:00',
    },
    {
      clave: 'NT301',
      nombre: 'Redes de Computadoras II',
      creditos: 8,
      profesor: 'Dr. Vint Cerf',
      dias: 'Lun, Vie',
      horario: '12:00 - 14:00',
    },
    {
      clave: 'SE401',
      nombre: 'Ingeniería de Software',
      creditos: 6,
      profesor: 'Dra. Margaret Hamilton',
      dias: 'Mar, Jue',
      horario: '14:00 - 16:00',
    },
    {
      clave: 'HU102',
      nombre: 'Ética Profesional',
      creditos: 4,
      profesor: 'Mtro. Roberto Flores',
      dias: 'Vie',
      horario: '10:00 - 14:00',
    },
  ],
};
